name: orchids_emporium_web_admin
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  firebase_core: ^2.10.0
  cloud_firestore: 4.5.2
  firebase_auth: ^4.4.2
  firebase_storage: 11.1.1
  flutter_admin_scaffold: 1.2.0
  google_fonts: 4.0.3
  image_picker: 1.0.1
  file_picker: 5.2.11
  flutter_image_compress: 2.0.4
  awesome_snackbar_content: 0.1.3
  firebase_ui_auth: 1.4.2
  flutter_signin_button: 2.0.0
  fluttertoast: 8.2.2
  firebase_dynamic_links: 5.3.2
  country_state_city_picker: 1.2.8
  flutter_easyloading: 3.0.5
  firebase_ui_oauth_google: 1.2.2
  rxdart: 0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

