name: orchids_emporium
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  flutter_screenutil: 5.8.4
  awesome_bottom_bar: 1.2.2
  google_fonts: ^4.0.3
  firebase_core: ^2.10.0
  cloud_firestore: 4.5.2
  firebase_auth: ^4.4.2
  firebase_storage: 11.1.1
  image_picker: 0.8.7+4
  flutter_image_compress: 2.0.4
  cached_network_image: 3.2.3
  shimmer_animation: 2.1.0+1
  firebase_ui_auth: 1.4.3
  fluttertoast: 8.2.2
  country_state_city_picker: 1.2.8
  flutter_easyloading: 3.0.5
  firebase_ui_oauth_google: 1.2.2
  provider: 6.0.5
  uuid: 3.0.7
  intl: 0.18.0
  photo_view: 0.14.0
  smooth_page_indicator: 1.1.0
  flutter_slidable: 3.0.0
  syncfusion_flutter_gauges: 22.1.39
  animated_notch_bottom_bar: 1.0.0
  flutter_launcher_icons: ^0.13.1
  http: 1.1.0
  flutter_stripe: ^9.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

